apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-collap-app 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-collap-app 
  template:
    metadata:
      labels:
        app: k8s-collap-app
    spec:
      containers:
      - name: k8s-collap-app-container
        image: ghcr.io/tsafac/k8s-collap-app:latest
        ports:
          - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-secret
        
